### ISSUE TITLE
Failed to call service get_planning_scene

### ISSUE THREAD

**Issue by howardjchen** [kentsai0319/techman_robot#1]
Hi, recently I cloned this repository and try to 
```
roslaunch tm700_moveit_config tm700_moveit_planning_execution.launch 
```
but I met some problem in the following pictures:
![](https://i.imgur.com/RYnqfEb.png)
- it appearse **NO PLANNING LIBRARY LOADED**
![](https://i.imgur.com/P8KZIiN.png)
- this is the rqt_graph
- ![](https://i.imgur.com/0l2VVXJ.png)

- However, I found out that if I use the older verion this repository, everythin went really well. Therefore, I'm not sure where gose wrong.
Many thanks.

**Comment by yhtsai** [comment]
This is because I re-run the moveit config with moveit-0.7.6. Current commit should work for moveit-0.7.2 too.

**Comment by howardjchen** [comment]
It works. Thanks a lot
